  const bibleVerses = [

{ ref: "Genesis 1:1", text: "In the beginning, God created the heavens and the earth, revealing His power and divine order over all creation." },
{ ref: "Genesis 1:3", text: "God spoke light into existence, showing His word brings life, clarity, and direction into darkness and confusion." },
{ ref: "Genesis 1:27", text: "God created humanity in His own image, male and female, giving us worth, purpose, and divine reflection." },
{ ref: "Genesis 2:7", text: "The Lord formed man from the dust and breathed life into him, showing His closeness and gift of life." },
{ ref: "Genesis 12:2", text: "God promised to make Abram a great nation, blessing him so that he could be a blessing to others." },
{ ref: "Genesis 15:6", text: "Abram believed in the Lord’s promise, and God counted his faith as righteousness, showing faith’s power before deeds." },
{ ref: "Genesis 18:14", text: "God reminds us that nothing is too difficult for Him; His timing and promises always bring life and hope." },
{ ref: "Genesis 50:20", text: "What others intended for harm, God turned into good, proving His sovereignty even through pain and injustice." },
{ ref: "Exodus 14:14", text: "The Lord Himself will fight for you; your role is to rest in faith and remain still in trust." },
{ ref: "Exodus 15:2", text: "The Lord is my strength and song; He has become my salvation and fills my heart with praise." },
{ ref: "Exodus 20:3", text: "You shall have no other gods before Me, for only God deserves our full worship, trust, and devotion." },
{ ref: "Exodus 33:14", text: "God promises His presence to go with us and give rest, reminding us peace comes through His nearness." },
{ ref: "Leviticus 19:18", text: "Love your neighbor as yourself, choosing compassion and forgiveness, for this reflects the heart and nature of God." },
{ ref: "Numbers 6:24", text: "The Lord bless you and keep you, surrounding you with favor, protection, and His faithful love each day." },
{ ref: "Deuteronomy 6:5", text: "Love the Lord your God with all your heart, soul, and strength, giving Him your full devotion and trust." },
{ ref: "Deuteronomy 31:6", text: "Be strong and courageous; the Lord your God goes with you and will never leave or abandon you." },
{ ref: "Joshua 1:9", text: "Be bold and unafraid; the Lord your God is with you wherever you go, strengthening your heart in courage." },
{ ref: "Joshua 24:15", text: "Choose this day whom you will serve, but as for me and my household, we will serve the Lord faithfully." },
{ ref: "Judges 6:12", text: "The angel said, 'The Lord is with you, mighty warrior,' reminding us God sees strength even when we feel weak." },
{ ref: "Ruth 1:16", text: "Where you go, I will go; your people will be my people, and your God will be my God forever." },
{ ref: "1 Samuel 16:7", text: "Man looks at outward appearance, but the Lord sees the heart, valuing our inner character over visible things." },
{ ref: "2 Samuel 22:31", text: "God’s way is perfect; His word flawless, a shield to all who take refuge and trust in Him." },
{ ref: "1 Kings 8:61", text: "Let your hearts be fully devoted to the Lord, walking faithfully in all His ways without wavering." },
{ ref: "1 Kings 17:14", text: "God promised the widow her jar of flour would not run dry, showing His faithfulness in desperate times." },
{ ref: "2 Kings 20:5", text: "I have heard your prayer and seen your tears, says the Lord, bringing healing and hope to your heart." },
{ ref: "1 Chronicles 16:11", text: "Seek the Lord and His strength; continually pursue His presence, for He alone sustains and renews you." },
{ ref: "2 Chronicles 7:14", text: "If My people humble themselves and pray, I will hear from heaven, forgive their sin, and heal their land." },
{ ref: "Ezra 10:4", text: "Rise up with courage and act, for God is with you to strengthen your heart and lead your way." },
{ ref: "Nehemiah 8:10", text: "Do not grieve, for the joy of the Lord is your strength and your source of endurance and peace." },
{ ref: "Esther 4:14", text: "Perhaps you were born for such a time as this, placed here by God to fulfill His divine purpose." },
{ ref: "Job 1:21", text: "The Lord gave and the Lord has taken away; blessed be His name in every circumstance and season." },
{ ref: "Job 19:25", text: "I know my Redeemer lives, and in the end He will stand victorious upon the earth forevermore." },
{ ref: "Psalm 1:2", text: "Blessed is the one whose delight is in God’s Word, meditating on His truth day and night." },
{ ref: "Psalm 4:8", text: "In peace I will lie down and sleep, for You alone, Lord, make me dwell in safety and rest." },
{ ref: "Psalm 9:9", text: "The Lord is a refuge for the oppressed, a stronghold in times of trouble and distress." },
{ ref: "Psalm 16:8", text: "I keep the Lord always before me; with Him at my right hand, I will not be shaken." },
{ ref: "Psalm 18:2", text: "The Lord is my rock, fortress, and deliverer; my shield and stronghold in every storm of life." },
{ ref: "Psalm 19:1", text: "The heavens declare God’s glory; the skies proclaim His handiwork, revealing His beauty in creation’s design." },
{ ref: "Psalm 23:1", text: "The Lord is my shepherd; I lack nothing, for He provides and guides me through every season." },
{ ref: "Psalm 27:1", text: "The Lord is my light and salvation—whom shall I fear? He is my strength and defender forever." },
{ ref: "Psalm 28:7", text: "The Lord is my strength and shield; my heart trusts in Him, and He fills me with joy." },
{ ref: "Psalm 30:5", text: "Weeping may stay for the night, but joy comes in the morning through the faithful mercy of God." },
{ ref: "Psalm 31:24", text: "Be strong and take heart, all who hope in the Lord, for His promises never fail." },
{ ref: "Psalm 34:8", text: "Taste and see that the Lord is good; blessed are those who trust and take refuge in Him." },
{ ref: "Psalm 37:4", text: "Delight yourself in the Lord, and He will give you the desires of your heart as you walk with Him." },
{ ref: "Psalm 46:1", text: "God is our refuge and strength, an ever-present help in trouble, a safe haven in every storm." },
{ ref: "Psalm 51:10", text: "Create in me a clean heart, O God, and renew a right spirit within me daily." },
{ ref: "Psalm 55:22", text: "Cast your cares upon the Lord, and He will sustain you; He never lets the righteous fall." },
{ ref: "Psalm 56:3", text: "When I am afraid, I will trust in You, for Your presence drives out fear and anxiety." },
{ ref: "Psalm 62:1", text: "My soul finds rest in God alone; my salvation and peace come from Him." },
{ ref: "Psalm 91:2", text: "I declare the Lord is my refuge and fortress, my God in whom I place all trust." },
{ ref: "Psalm 100:2", text: "Serve the Lord with gladness; come before His presence with joyful singing and a thankful heart." },
{ ref: "Psalm 118:24", text: "This is the day the Lord has made; we will rejoice and be glad in His goodness." },
{ ref: "Psalm 119:11", text: "I have hidden Your word in my heart, that I might not sin against You." },
{ ref: "Psalm 121:2", text: "My help comes from the Lord, the Maker of heaven and earth, my ever-present protector." },
{ ref: "Psalm 136:1", text: "Give thanks to the Lord, for He is good; His steadfast love endures forever and never fades." },
{ ref: "Proverbs 3:5", text: "Trust in the Lord with all your heart and lean not on your own understanding or wisdom." },
{ ref: "Proverbs 3:6", text: "In all your ways acknowledge Him, and He will direct your paths with wisdom and clarity." },
{ ref: "Proverbs 4:23", text: "Guard your heart above all else, for it determines the direction and outcome of your life." },
{ ref: "Proverbs 9:10", text: "The fear of the Lord is the beginning of wisdom, and knowledge of Him brings true understanding." },
{ ref: "Proverbs 10:12", text: "Hatred stirs up conflict, but love covers all wrongs and heals relationships with grace." },
{ ref: "Proverbs 11:25", text: "A generous person will prosper; whoever refreshes others will themselves be refreshed by God’s kindness." },
{ ref: "Proverbs 12:25", text: "Anxiety weighs down the heart, but a kind word brings joy and lifts the soul." },
{ ref: "Proverbs 15:1", text: "A gentle answer turns away wrath, but harsh words stir up anger and division." },
{ ref: "Proverbs 16:3", text: "Commit your work to the Lord, and He will establish and bless your plans." },
{ ref: "Proverbs 17:17", text: "A friend loves at all times, and a brother is born for times of adversity and trial." },
{ ref: "Proverbs 18:10", text: "The name of the Lord is a strong tower; the righteous run to it and are safe." },
{ ref: "Proverbs 19:21", text: "Many plans fill a person’s heart, but it is the Lord’s purpose that always prevails." },
{ ref: "Proverbs 27:17", text: "As iron sharpens iron, so friends strengthen and refine one another through truth and encouragement." },
{ ref: "Ecclesiastes 3:1", text: "To everything there is a season and a purpose under heaven, showing God’s order in life’s timing." },
{ ref: "Isaiah 26:3", text: "You keep in perfect peace those whose minds remain steadfast because they trust completely in You." },
{ ref: "Isaiah 40:8", text: "The grass withers and the flowers fade, but the Word of our God stands firm forever." },
{ ref: "Isaiah 40:31", text: "Those who hope in the Lord will renew their strength; they will soar on wings like eagles." },
{ ref: "Isaiah 41:10", text: "Do not fear, for I am with you; I will strengthen, help, and uphold you with My righteous hand." },
{ ref: "Isaiah 43:2", text: "When you pass through deep waters, I will be with you; you will not be overwhelmed." },
{ ref: "Isaiah 55:6", text: "Seek the Lord while He may be found; call upon Him while He is near and listening." },
{ ref: "Isaiah 60:1", text: "Arise, shine, for your light has come, and the glory of the Lord rises upon you." },
{ ref: "Jeremiah 29:11", text: "I know the plans I have for you, says the Lord, plans for hope and a future." },
{ ref: "Lamentations 3:22", text: "Because of the Lord’s great love we are not consumed; His mercies never fail and are new every morning." },
{ ref: "Ezekiel 36:26", text: "I will give you a new heart and spirit, removing your heart of stone and making it tender again." },
{ ref: "Daniel 2:20", text: "Blessed be the name of God forever; wisdom and power belong to Him alone." },
{ ref: "Hosea 6:6", text: "I desire mercy, not sacrifice, and acknowledgment of God rather than mere rituals or empty offerings." },
{ ref: "Joel 2:32", text: "Everyone who calls upon the name of the Lord will be saved and find refuge in His mercy." },
{ ref: "Amos 5:24", text: "Let justice roll down like waters and righteousness flow like a mighty, never-ending stream." },
{ ref: "Micah 6:8", text: "Do justice, love mercy, and walk humbly with your God, for this is what He requires of you." },
{ ref: "Nahum 1:7", text: "The Lord is good, a refuge in times of trouble; He cares for those who trust in Him." },
{ ref: "Habakkuk 3:19", text: "The Lord is my strength; He makes my feet like deer’s and enables me to tread on heights." },
{ ref: "Zephaniah 3:17", text: "The Lord your God is with you, mighty to save; He rejoices over you with singing and love." },
{ ref: "Zechariah 4:6", text: "Not by might nor by power, but by My Spirit, says the Lord Almighty, your true strength." },
{ ref: "Malachi 3:10", text: "Bring the whole tithe into the storehouse and see if I won’t open heaven’s windows with overflowing blessing." },
{ ref: "Matthew 5:14", text: "You are the light of the world; let your good deeds shine so others may glorify your Father in heaven." },
{ ref: "Matthew 6:33", text: "Seek first the kingdom of God and His righteousness, and all these things will be added to you." },
{ ref: "Matthew 7:7", text: "Ask and it will be given; seek and you will find; knock and the door will be opened." },
{ ref: "Matthew 11:28", text: "Come to Me, all who are weary and burdened, and I will give you rest and peace." },
{ ref: "Matthew 19:26", text: "With man this is impossible, but with God all things are possible and within His mighty power." },
{ ref: "Mark 9:23", text: "All things are possible for the one who believes; faith opens the way to divine possibilities." },
{ ref: "Luke 1:37", text: "Nothing is impossible with God; His word always accomplishes what He promises in perfect timing." },
{ ref: "John 3:16", text: "For God so loved the world that He gave His only Son, offering eternal life to all who believe." },
{ ref: "John 8:12", text: "Jesus said, 'I am the light of the world; whoever follows Me will never walk in darkness again.'" },
{ ref: "John 14:6", text: "Jesus declared, 'I am the way, the truth, and the life; no one comes to the Father except through Me.'" },
{ ref: "John 11:35", text: "Jesus wept, showing that even the Son of God feels our pain and shares deeply in our sorrow and compassion." },
{ ref: "John 15:5", text: "I am the vine; you are the branches. Apart from Me, you can do nothing that truly lasts." },
{ ref: "Acts 1:8", text: "You will receive power when the Holy Spirit comes upon you, and you will be My witnesses to the world." },
{ ref: "Acts 2:21", text: "Everyone who calls upon the name of the Lord shall be saved through His grace and mercy." },
{ ref: "Acts 4:12", text: "Salvation is found in no one else, for only Jesus’ name brings eternal life and forgiveness of sins." },
{ ref: "Acts 16:31", text: "Believe in the Lord Jesus Christ, and you will be saved—you and your entire household will find grace." },
{ ref: "Romans 1:16", text: "I am not ashamed of the gospel, for it is the power of God that brings salvation to all who believe." },
{ ref: "Romans 3:23", text: "All have sinned and fall short of the glory of God, yet grace restores and redeems through faith." },
{ ref: "Romans 5:8", text: "While we were still sinners, Christ died for us, proving His incredible love and mercy beyond all measure." },
{ ref: "Romans 6:23", text: "The wages of sin is death, but God’s free gift is eternal life through Jesus Christ our Lord." },
{ ref: "Romans 8:1", text: "There is now no condemnation for those who are in Christ Jesus, who sets us free from sin and death." },
{ ref: "Romans 8:28", text: "We know that all things work together for good for those who love God and walk in His purpose." },
{ ref: "Romans 10:9", text: "If you confess with your mouth Jesus is Lord and believe in your heart, you will be saved." },
{ ref: "Romans 12:2", text: "Do not conform to this world but be transformed by renewing your mind to discern God’s good and perfect will." },
{ ref: "1 Corinthians 1:9", text: "God is faithful, who has called you into fellowship with His Son, Jesus Christ our Lord." },
{ ref: "1 Corinthians 2:9", text: "No eye has seen, no ear has heard, what God has prepared for those who love Him." },
{ ref: "1 Corinthians 6:19", text: "Your body is a temple of the Holy Spirit, who lives in you; honor God with your life." },
{ ref: "1 Corinthians 10:13", text: "God is faithful and will not let you be tempted beyond what you can bear; He provides a way out." },
{ ref: "1 Corinthians 13:4", text: "Love is patient and kind; it does not envy or boast, and it is not proud or selfish." },
{ ref: "1 Corinthians 15:57", text: "Thanks be to God, who gives us victory through our Lord Jesus Christ and His resurrection power." },
{ ref: "2 Corinthians 1:3", text: "Blessed be the God of all comfort, who comforts us in every trouble so we may comfort others." },
{ ref: "2 Corinthians 4:18", text: "We fix our eyes not on what is seen but unseen, for what is unseen is eternal and lasting." },
{ ref: "2 Corinthians 5:7", text: "We walk by faith, not by sight, trusting God’s guidance even when we do not understand His ways." },
{ ref: "2 Corinthians 5:17", text: "If anyone is in Christ, he is a new creation; the old has gone, the new has come." },
{ ref: "2 Corinthians 12:9", text: "My grace is sufficient for you, for My power is made perfect in weakness; rely on Me completely." },
{ ref: "Galatians 2:20", text: "I have been crucified with Christ; it is no longer I who live, but Christ lives in me forever." },
{ ref: "Galatians 5:22", text: "The fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control." },
{ ref: "Ephesians 2:8", text: "By grace you have been saved through faith; it is the gift of God, not from works or merit." },
{ ref: "Ephesians 3:20", text: "God can do exceedingly and abundantly above all we ask or imagine, according to His power within us." },
{ ref: "Ephesians 4:32", text: "Be kind and compassionate to one another, forgiving each other just as God forgave you through Christ." },
{ ref: "Ephesians 6:11", text: "Put on the full armor of God so that you can stand firm against the devil’s schemes." },
{ ref: "Philippians 1:6", text: "He who began a good work in you will carry it on to completion until the day of Christ Jesus." },
{ ref: "Philippians 2:3", text: "Do nothing out of selfish ambition or pride, but in humility value others above yourself." },
{ ref: "Philippians 4:4", text: "Rejoice in the Lord always; again I say, rejoice, for joy in Him never fades." },
{ ref: "Philippians 4:6", text: "Do not be anxious about anything, but in prayer and thanksgiving, make your requests known to God." },
{ ref: "Philippians 4:13", text: "I can do all things through Christ who gives me strength, courage, and endurance through every trial." },
{ ref: "Colossians 3:2", text: "Set your minds on things above, not on earthly things, for your life is hidden with Christ in God." },
{ ref: "Colossians 3:23", text: "Whatever you do, work heartily as for the Lord, not for men, for He is your reward." },
{ ref: "1 Thessalonians 5:16", text: "Rejoice always, keeping your heart lifted in gratitude and trust before God no matter your circumstances." },
{ ref: "1 Thessalonians 5:17", text: "Pray without ceasing, staying in constant communion with God through every moment of your life." },
{ ref: "1 Thessalonians 5:18", text: "Give thanks in all circumstances, for this is God’s will for you in Christ Jesus." },
{ ref: "2 Thessalonians 3:3", text: "The Lord is faithful; He will strengthen you and guard you from the evil one." },
{ ref: "1 Timothy 4:12", text: "Let no one despise your youth, but set an example in speech, conduct, love, faith, and purity." },
{ ref: "2 Timothy 1:7", text: "God has not given us a spirit of fear, but of power, love, and a sound mind." },
{ ref: "2 Timothy 3:16", text: "All Scripture is God-breathed and useful for teaching, rebuking, correcting, and training in righteousness." },
{ ref: "Titus 2:11", text: "The grace of God has appeared, bringing salvation to all and teaching us to live godly lives." },
{ ref: "Philemon 1:7", text: "Your love has given me great joy and encouragement, for you have refreshed the hearts of the saints." },
{ ref: "Hebrews 4:12", text: "The word of God is living and active, sharper than any sword, judging thoughts and attitudes of the heart." },
{ ref: "Hebrews 10:23", text: "Let us hold fast the confession of our hope without wavering, for God is faithful to His promises." },
{ ref: "Hebrews 11:1", text: "Faith is the assurance of what we hope for and the conviction of what we do not see." },
{ ref: "Hebrews 12:1", text: "Let us run with endurance the race before us, fixing our eyes on Jesus, the author and finisher of faith." },
{ ref: "James 1:2", text: "Consider it pure joy when you face trials, because testing of faith produces perseverance and maturity." },
{ ref: "James 1:5", text: "If anyone lacks wisdom, ask God, who gives generously to all without finding fault, and it will be given." },
{ ref: "James 2:17", text: "Faith by itself, if not accompanied by action, is dead and bears no fruit in God’s eyes." },
{ ref: "James 4:7", text: "Submit yourselves to God. Resist the devil, and he will flee from you in defeat." },
{ ref: "1 Peter 1:3", text: "Praise be to God who, in His mercy, has given us new birth into a living hope through Jesus Christ." },
{ ref: "1 Peter 2:9", text: "You are a chosen people, a royal priesthood, called to proclaim the praises of Him who saved you." },
{ ref: "1 Peter 3:15", text: "Always be ready to give an answer for your hope, doing so with gentleness and respect." },
{ ref: "1 Peter 5:7", text: "Cast all your anxiety on Him, because He cares for you deeply and without fail." },
{ ref: "1 Peter 5:10", text: "After you have suffered a little, the God of grace will restore, strengthen, and establish you." },
{ ref: "2 Peter 3:9", text: "The Lord is patient, not wanting anyone to perish, but for all to come to repentance." },
{ ref: "1 John 1:9", text: "If we confess our sins, He is faithful and just to forgive us and cleanse us from unrighteousness." },
{ ref: "1 John 3:1", text: "See what great love the Father has lavished on us, that we should be called children of God." },
{ ref: "1 John 4:7", text: "Beloved, let us love one another, for love comes from God, and everyone who loves is born of Him." },
{ ref: "1 John 4:18", text: "Perfect love drives out fear, because fear has to do with punishment, and God’s love brings peace." },
{ ref: "1 John 5:4", text: "Everyone born of God overcomes the world; this is the victory that overcomes—our faith in Christ Jesus." },
{ ref: "2 John 1:6", text: "This is love: that we walk in obedience to His commands and live in His truth." },
{ ref: "3 John 1:4", text: "I have no greater joy than to hear that my children are walking in the truth of Christ." },
{ ref: "Jude 1:21", text: "Keep yourselves in the love of God as you wait for the mercy of Jesus Christ to bring eternal life." },
{ ref: "Revelation 1:8", text: "I am the Alpha and the Omega, says the Lord God, who is, who was, and who is to come." },
{ ref: "Revelation 3:20", text: "Behold, I stand at the door and knock; if anyone hears My voice and opens, I will come in." },
{ ref: "Revelation 7:17", text: "The Lamb at the center of the throne will shepherd them and wipe away every tear from their eyes." },
{ ref: "Revelation 12:11", text: "They overcame him by the blood of the Lamb and by the word of their testimony of faith." },
{ ref: "Revelation 21:4", text: "He will wipe every tear from their eyes, and there will be no more death, sorrow, or pain." },
{ ref: "Revelation 22:13", text: "I am the Alpha and the Omega, the First and the Last, the Beginning and the End." },
{ ref: "Psalm 27:14", text: "Wait for the Lord; be strong and take heart, and trust His perfect timing for everything." },
{ ref: "Psalm 32:8", text: "I will instruct and teach you in the way you should go; I will counsel you with love." },
{ ref: "Psalm 42:11", text: "Why are you downcast, my soul? Put your hope in God, for I will yet praise Him again." },
{ ref: "Psalm 103:12", text: "As far as the east is from the west, so far has He removed our sins from us forever." },
{ ref: "Psalm 119:105", text: "Your word is a lamp to my feet and a light to my path, guiding me with wisdom." },
{ ref: "Proverbs 11:30", text: "The fruit of the righteous is a tree of life, and whoever wins souls is wise before God." },
{ ref: "Isaiah 53:5", text: "He was pierced for our transgressions and crushed for our iniquities; by His wounds we are healed." },
{ ref: "Jeremiah 33:3", text: "Call to Me, and I will answer you, showing great and hidden things you do not know." },
{ ref: "Daniel 3:17", text: "Our God is able to deliver us, but even if He does not, we will not bow to idols." },
{ ref: "Jonah 2:2", text: "In my distress, I called to the Lord, and He answered me from the depths of my despair." },
{ ref: "Matthew 5:9", text: "Blessed are the peacemakers, for they will be called children of God who reflect His character." },
{ ref: "Matthew 9:37", text: "The harvest is plentiful, but the workers are few; pray for God to send more laborers." },
{ ref: "Luke 6:31", text: "Do to others as you would have them do to you, living with kindness and fairness in all." },
{ ref: "Luke 10:27", text: "Love the Lord your God with all your heart and your neighbor as yourself in genuine compassion." },
{ ref: "Luke 12:34", text: "Where your treasure is, there your heart will be also; set your affections on eternal things." },
{ ref: "Luke 18:27", text: "What is impossible with man is possible with God, for nothing limits His power or love." },
{ ref: "John 10:10", text: "The thief comes only to steal and destroy, but I have come that they may have life abundantly." },
{ ref: "Acts 20:35", text: "It is more blessed to give than to receive, for generosity reflects the heart of Christ within us." },
{ ref: "Romans 15:13", text: "May the God of hope fill you with joy and peace as you trust in Him." },
{ ref: "1 Corinthians 15:58", text: "Stand firm, always giving yourself fully to God’s work, knowing your labor in the Lord is not in vain." },
{ ref: "Galatians 6:9", text: "Let us not grow weary in doing good, for at the right time we will reap a harvest." },
{ ref: "Ephesians 4:1", text: "Walk worthy of your calling, with humility, gentleness, and patience, bearing with one another in love." },
{ ref: "Philippians 3:14", text: "I press on toward the goal to win the prize for which God has called me heavenward in Christ." },
{ ref: "Colossians 2:6", text: "As you received Christ Jesus as Lord, continue to live in Him, rooted and built up in faith." },
{ ref: "Genesis 28:15", text: "I am with you and will watch over you wherever you go, never leaving nor forsaking you." },
{ ref: "Exodus 3:14", text: "God said, 'I AM WHO I AM,' revealing His eternal, unchanging presence and authority over all creation." },
{ ref: "Exodus 20:12", text: "Honor your father and mother so that your days may be long in the land the Lord gives you." },
{ ref: "Leviticus 19:2", text: "Be holy because I, the Lord your God, am holy and call you to reflect My purity." },
{ ref: "Deuteronomy 31:8", text: "The Lord goes before you and will be with you; do not fear or be discouraged." },
{ ref: "Joshua 23:14", text: "Not one promise of the Lord has failed; every word He spoke has come to pass faithfully." },
{ ref: "Judges 2:18", text: "Whenever the Lord raised up judges, He was with them and saved the people from their enemies." },
{ ref: "Ruth 2:12", text: "May the Lord reward you fully for your kindness; under His wings, you have taken refuge." },
{ ref: "1 Samuel 12:24", text: "Fear the Lord and serve Him faithfully with all your heart; consider what great things He has done." },
{ ref: "2 Samuel 22:33", text: "It is God who arms me with strength and makes my way secure through every trial I face." },
{ ref: "1 Kings 2:3", text: "Walk in obedience to the Lord, keeping His commands and decrees so that you may prosper in all." },
{ ref: "2 Kings 17:39", text: "Worship the Lord your God; He will deliver you from the hands of all your enemies." },
{ ref: "1 Chronicles 29:11", text: "Yours, Lord, is the greatness and power, for all things in heaven and earth belong to You." },
{ ref: "2 Chronicles 16:9", text: "The eyes of the Lord range throughout the earth to strengthen those fully committed to Him." },
{ ref: "Ezra 8:22", text: "The gracious hand of our God is on everyone who seeks Him with humble and faithful hearts." },
{ ref: "Nehemiah 1:11", text: "Lord, let Your ear be attentive to the prayer of Your servant and grant success to Your people." },
{ ref: "Esther 2:17", text: "The king loved Esther above all others, and she found favor and grace before him." },
{ ref: "Job 23:10", text: "He knows the way I take; when He has tested me, I will come forth as gold refined." },
{ ref: "Job 42:2", text: "I know that You can do all things; no purpose of Yours can ever be thwarted." },
{ ref: "Psalm 19:14", text: "May the words of my mouth and meditation of my heart be pleasing in Your sight, O Lord." },
{ ref: "Psalm 25:4", text: "Show me Your ways, O Lord; teach me Your paths and guide me in Your truth." },
{ ref: "Psalm 46:10", text: "Be still and know that I am God; I will be exalted among the nations and in the earth." },
{ ref: "Psalm 73:26", text: "My flesh and heart may fail, but God is the strength of my heart and my portion forever." },
{ ref: "Psalm 84:10", text: "Better is one day in Your courts than a thousand elsewhere; I would rather stand at Your door." },
{ ref: "Psalm 91:4", text: "He will cover you with His feathers, and under His wings you will find refuge and safety." },
{ ref: "Psalm 119:50", text: "My comfort in suffering is this: Your promise preserves my life and gives me hope again." },
{ ref: "Psalm 138:8", text: "The Lord will fulfill His purpose for me; Your love endures forever, O Lord, do not abandon me." },
{ ref: "Proverbs 1:7", text: "The fear of the Lord is the beginning of knowledge; fools despise wisdom and instruction." },
{ ref: "Proverbs 14:12", text: "There is a way that seems right to man, but in the end it leads to death." },
{ ref: "Proverbs 16:9", text: "In their hearts humans plan their course, but the Lord establishes their steps according to His will." },
{ ref: "Proverbs 18:21", text: "The tongue has the power of life and death, and those who love it will eat its fruit." },
{ ref: "Proverbs 21:21", text: "Whoever pursues righteousness and love finds life, prosperity, and honor in the eyes of the Lord." },
{ ref: "Ecclesiastes 7:14", text: "When times are good, be joyful; when bad, consider that God made both to teach wisdom." },
{ ref: "Isaiah 1:18", text: "Though your sins are like scarlet, they shall be as white as snow through My forgiveness and mercy." },
{ ref: "Isaiah 26:4", text: "Trust in the Lord forever, for the Lord Himself is the eternal Rock that never fails." },
{ ref: "Isaiah 30:15", text: "In repentance and rest is your salvation; in quietness and trust is your strength, says the Lord." },
{ ref: "Isaiah 41:13", text: "I am the Lord your God, who takes your hand and says, 'Do not fear; I will help you.'" },
{ ref: "Isaiah 43:1", text: "Fear not, for I have redeemed you; I have called you by name, and you are Mine." },
{ ref: "Jeremiah 1:5", text: "Before I formed you in the womb, I knew you; before you were born, I set you apart." },
{ ref: "Jeremiah 17:7", text: "Blessed is the one who trusts in the Lord, whose confidence is firmly placed in Him alone." },
{ ref: "Jeremiah 20:9", text: "His word is in my heart like fire, a burning flame that I cannot hold back." },
{ ref: "Lamentations 3:23", text: "His mercies are new every morning; great is Your faithfulness, O Lord, my strength and redeemer." },
{ ref: "Ezekiel 37:5", text: "This is what the Lord says: I will make breath enter you, and you will come to life again." },
{ ref: "Daniel 6:27", text: "He rescues and saves; He performs signs and wonders in heaven and on earth with great power." },
{ ref: "Hosea 14:9", text: "The ways of the Lord are right; the righteous walk in them, but the rebellious stumble in sin." },
{ ref: "Joel 2:25", text: "I will restore the years the locusts have eaten, says the Lord, bringing renewal and hope again." },
{ ref: "Amos 5:14", text: "Seek good, not evil, that you may live, and the Lord will be with you as you do right." },
{ ref: "Micah 7:7", text: "As for me, I watch in hope for the Lord; I wait for God my Savior to answer." },
{ ref: "Nahum 1:3", text: "The Lord is slow to anger but great in power; He will not leave the guilty unpunished." },
{ ref: "Habakkuk 2:4", text: "The righteous shall live by faith, trusting in God’s promises even when the world seems dark." },
{ ref: "Zephaniah 3:17", text: "The Lord your God is with you; He rejoices over you with singing and delights in you with love." },
{ ref: "Haggai 2:9", text: "The glory of this present house will be greater than the former, and I will grant peace there." },
{ ref: "Zechariah 9:9", text: "See, your King comes to you righteous and victorious, humble and riding on a donkey, bringing peace." },
{ ref: "Malachi 4:2", text: "The Sun of Righteousness will rise with healing in His wings for all who revere My name." },
{ ref: "Matthew 5:16", text: "Let your light shine before others so they may see your good deeds and glorify your Father in heaven." },
{ ref: "Matthew 6:21", text: "Where your treasure is, there your heart will be also; store your treasures in heaven, not earth." },
{ ref: "Matthew 7:12", text: "Do to others what you would have them do to you; this sums up the Law and the Prophets." },
{ ref: "Matthew 22:37", text: "Love the Lord your God with all your heart, soul, and mind—this is the greatest commandment of all." },
{ ref: "Matthew 28:19", text: "Go and make disciples of all nations, baptizing them in the name of the Father, Son, and Spirit." },
{ ref: "Mark 10:45", text: "The Son of Man came not to be served but to serve and give His life as ransom for many." },
{ ref: "Luke 1:45", text: "Blessed is she who believed that the Lord would fulfill what He has spoken to her in faith." },
{ ref: "Luke 2:14", text: "Glory to God in the highest, and on earth peace to those on whom His favor rests." },
{ ref: "Luke 11:9", text: "Ask and it will be given to you; seek and you will find; knock and the door will open." },
{ ref: "Luke 22:42", text: "Father, not My will but Yours be done; Jesus modeled perfect surrender to God’s plan of redemption." },
{ ref: "John 1:12", text: "To all who received Him, He gave the right to become children of God, believing in His name." },
{ ref: "John 6:35", text: "I am the bread of life; whoever comes to Me will never hunger, and whoever believes will never thirst." },
{ ref: "John 13:34", text: "A new command I give you: Love one another as I have loved you, so you must love others." },
{ ref: "John 15:13", text: "Greater love has no one than this: to lay down one’s life for one’s friends in pure sacrifice." },
{ ref: "Acts 17:28", text: "In Him we live and move and have our being, for we are His offspring and belong to Him." },
{ ref: "Romans 8:38", text: "Nothing can separate us from God’s love—not death, life, angels, or powers—His love endures forever." },
{ ref: "1 Corinthians 10:31", text: "Whatever you do, do it all for the glory of God, making every act a reflection of His goodness." },
{ ref: "2 Corinthians 9:7", text: "God loves a cheerful giver; give freely and joyfully, for generosity reflects the heart of Christ within you." },
{ ref: "Galatians 5:1", text: "It is for freedom that Christ has set us free; stand firm and do not be burdened again by slavery." },
{ ref: "Ephesians 5:2", text: "Walk in the way of love, just as Christ loved us and gave Himself up for us as a sacrifice." },
{ ref: "Philippians 2:13", text: "It is God who works in you to will and to act in order to fulfill His good purpose." },
{ ref: "Colossians 1:17", text: "He is before all things, and in Him all things hold together perfectly by His divine power and wisdom." },
{ ref: "1 Thessalonians 4:16", text: "The Lord Himself will descend from heaven with a shout, and the dead in Christ will rise first." },
{ ref: "2 Thessalonians 2:16", text: "May our Lord Jesus Christ Himself encourage your hearts and strengthen you in every good deed and word." },
{ ref: "1 Timothy 6:12", text: "Fight the good fight of faith; take hold of the eternal life to which you were called by grace." },
{ ref: "2 Timothy 2:13", text: "If we are faithless, He remains faithful, for He cannot deny Himself or fail His promises." },
{ ref: "Titus 3:5", text: "He saved us, not because of righteous things we have done, but through His mercy and renewal by the Spirit." },
{ ref: "Hebrews 6:19", text: "We have this hope as an anchor for the soul, firm and secure, reaching into the inner sanctuary of God." },
{ ref: "Hebrews 13:5", text: "God has said, 'Never will I leave you; never will I forsake you,' assuring us of His constant presence." },
{ ref: "James 4:8", text: "Draw near to God and He will draw near to you; purify your heart and humble yourself before Him." },
{ ref: "1 Peter 4:10", text: "Use whatever gift you have received to serve others, faithfully administering God’s grace in its many forms." },
{ ref: "2 Peter 1:3", text: "His divine power has given us everything we need for life and godliness through knowing Him who called us." },
{ ref: "1 John 2:17", text: "The world and its desires pass away, but whoever does the will of God lives forever." },
{ ref: "Revelation 2:10", text: "Be faithful unto death, and I will give you the crown of life as your eternal reward." },
{ ref: "Genesis 22:14", text: "Abraham called that place ‘The Lord Will Provide,’ for God always fulfills His promises and meets every need in faith." },
{ ref: "Genesis 50:21", text: "Do not be afraid; I will provide for you and your children, showing God’s redemptive mercy in forgiveness." },
{ ref: "Exodus 13:21", text: "By day the Lord went ahead in a pillar of cloud and by night in a pillar of fire guiding Israel." },
{ ref: "Exodus 34:6", text: "The Lord is compassionate and gracious, slow to anger, abounding in steadfast love and faithfulness for generations." },
{ ref: "Leviticus 20:26", text: "You are to be holy to Me, because I, the Lord, am holy and have set you apart as Mine." },
{ ref: "Numbers 23:19", text: "God is not a man that He should lie; He fulfills every word He has spoken faithfully and fully." },
{ ref: "Deuteronomy 7:9", text: "Know that the Lord your God is faithful, keeping His covenant of love to a thousand generations of believers." },
{ ref: "Joshua 21:45", text: "Not one of the Lord’s good promises failed; every single word came true in His perfect timing." },
{ ref: "Judges 7:15", text: "When Gideon heard the dream and its interpretation, he bowed in worship, trusting God’s victory against all odds." },
{ ref: "Ruth 4:14", text: "Blessed be the Lord, who has not left you without a redeemer, for He restores joy and legacy." },
{ ref: "1 Samuel 2:2", text: "There is no one holy like the Lord; there is no rock like our God who saves." },
{ ref: "2 Samuel 7:22", text: "How great You are, O Lord! There is none like You, and no God but You alone." },
{ ref: "1 Kings 3:9", text: "Give Your servant a discerning heart to govern Your people and distinguish between right and wrong in wisdom." },
{ ref: "2 Kings 19:19", text: "Now, Lord our God, deliver us so that all kingdoms may know You alone are God." },
{ ref: "1 Chronicles 16:34", text: "Give thanks to the Lord, for He is good; His steadfast love endures forever and never fails." },
{ ref: "2 Chronicles 20:15", text: "Do not be afraid or discouraged; the battle is not yours but God’s, who fights on your behalf." },
{ ref: "Ezra 7:10", text: "Ezra devoted himself to studying the Law of the Lord and to teaching His decrees to Israel faithfully." },
{ ref: "Nehemiah 2:20", text: "The God of heaven will give us success; we, His servants, will rise up and build with courage." },
{ ref: "Esther 8:17", text: "In every province, joy and celebration spread among the Jews, for God had turned their sorrow into gladness." },
{ ref: "Job 5:11", text: "He sets the lowly on high and lifts those who mourn to safety and strength through His compassion." },
{ ref: "Psalm 9:1", text: "I will give thanks to You, Lord, with all my heart; I will tell of Your wonderful deeds." },
{ ref: "Psalm 18:30", text: "As for God, His way is perfect; the Lord’s word is flawless, shielding all who take refuge in Him." },
{ ref: "Psalm 27:13", text: "I remain confident of this: I will see the goodness of the Lord in the land of the living." },
{ ref: "Psalm 40:1", text: "I waited patiently for the Lord; He turned to me and heard my cry, lifting me from despair." },
{ ref: "Psalm 51:12", text: "Restore to me the joy of Your salvation, and uphold me with a willing spirit to follow You." },
{ ref: "Psalm 63:3", text: "Because Your love is better than life, my lips will glorify You and my heart will cling to You." },
{ ref: "Psalm 86:5", text: "You, Lord, are forgiving and good, abounding in love to all who call upon You in faith." },
{ ref: "Psalm 103:8", text: "The Lord is compassionate and gracious, slow to anger and abounding in steadfast love for His children." },
{ ref: "Psalm 121:8", text: "The Lord will watch over your coming and going both now and forevermore with unfailing care." },
{ ref: "Proverbs 3:7", text: "Do not be wise in your own eyes; fear the Lord and turn away from evil in humility." },
{ ref: "Proverbs 12:28", text: "In the path of righteousness is life; along that way there is no death or destruction for the faithful." },
{ ref: "Proverbs 20:22", text: "Do not say, 'I’ll pay you back for this wrong!' Wait for the Lord, and He will deliver you." },
{ ref: "Ecclesiastes 12:13", text: "Fear God and keep His commandments, for this is the whole duty and purpose of mankind under heaven." },
{ ref: "Isaiah 9:6", text: "For to us a child is born, called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace forevermore." },
{ ref: "Isaiah 40:29", text: "He gives strength to the weary and increases the power of the weak who trust in Him." },
{ ref: "Isaiah 53:6", text: "We all, like sheep, have gone astray, but the Lord laid on Him the sin of us all." },
{ ref: "Isaiah 58:11", text: "The Lord will guide you continually, satisfy your needs, and strengthen your frame like a well-watered garden." },
{ ref: "Jeremiah 32:27", text: "I am the Lord, the God of all mankind. Is anything too hard for Me to accomplish?" },
{ ref: "Lamentations 3:25", text: "The Lord is good to those whose hope is in Him, to the one who seeks Him faithfully." },
{ ref: "Ezekiel 36:27", text: "I will put My Spirit in you and move you to follow My decrees and keep My laws with joy." },
{ ref: "Daniel 2:22", text: "He reveals deep and hidden things; He knows what lies in darkness, and light dwells with Him." },
{ ref: "Hosea 2:23", text: "I will show love to those called 'Not My People' and say, 'You are My people,' and they will respond." },
{ ref: "Joel 2:28", text: "I will pour out My Spirit on all people; your sons and daughters will prophesy and dream dreams." },
{ ref: "Amos 4:13", text: "He who forms the mountains and creates the wind declares His thoughts to man, the Lord Almighty is His name." },
{ ref: "Micah 4:5", text: "All nations may walk in their gods’ names, but we will walk in the name of the Lord forever." },
{ ref: "Nahum 1:15", text: "Look! On the mountains are the feet of one who brings good news, proclaiming peace from the Lord." },
{ ref: "Habakkuk 2:14", text: "The earth will be filled with the knowledge of the glory of the Lord as the waters cover the sea." },
{ ref: "Zephaniah 2:3", text: "Seek the Lord, all you humble of the earth, seek righteousness and humility that you may be sheltered." },
{ ref: "Haggai 1:13", text: "The Lord’s messenger said, 'I am with you,' declares the Lord, bringing courage to rebuild and restore the temple." },
{ ref: "Zechariah 8:13", text: "As you have been a curse among the nations, I will save you and make you a blessing again." },
{ ref: "Malachi 1:11", text: "My name will be great among the nations, says the Lord Almighty, from the rising to the setting sun." },
{ ref: "Matthew 11:29", text: "Take My yoke upon you and learn from Me, for I am gentle and humble in heart." },
{ ref: "Matthew 19:14", text: "Let the little children come to Me; do not hinder them, for the kingdom belongs to such as these." },
{ ref: "Mark 8:36", text: "What good is it for someone to gain the whole world, yet forfeit their soul in the end?" },
{ ref: "Luke 6:38", text: "Give, and it will be given to you; a good measure, pressed down, running over, poured into your lap." },
{ ref: "Luke 19:10", text: "The Son of Man came to seek and save the lost, revealing God’s boundless compassion for sinners." },
{ ref: "John 4:24", text: "God is Spirit, and His worshipers must worship in the Spirit and in truth sincerely and wholeheartedly." },
{ ref: "John 7:38", text: "Whoever believes in Me, rivers of living water will flow from within them, bringing life to others." },
{ ref: "John 14:27", text: "Peace I leave with you; My peace I give. Do not let your hearts be troubled or afraid." },
{ ref: "Acts 2:38", text: "Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of sins." },
{ ref: "Acts 20:24", text: "I consider my life worth nothing except finishing the race and task the Lord Jesus has given me." },
{ ref: "Romans 1:20", text: "God’s invisible qualities—eternal power and divine nature—are clearly seen in creation, leaving all without excuse." },
{ ref: "Romans 5:1", text: "Since we have been justified through faith, we have peace with God through our Lord Jesus Christ." },
{ ref: "Romans 8:15", text: "You received the Spirit of adoption, and by Him we cry, ‘Abba, Father,’ knowing we are loved children." },
{ ref: "Romans 14:8", text: "If we live, we live for the Lord; if we die, we die for the Lord—He owns us." },
{ ref: "1 Corinthians 1:25", text: "The foolishness of God is wiser than human wisdom, and the weakness of God stronger than human strength." },
{ ref: "2 Corinthians 5:1", text: "If our earthly tent is destroyed, we have a building from God, an eternal house not made with hands." },
{ ref: "Galatians 3:28", text: "There is neither Jew nor Gentile, slave nor free; all are one in Christ Jesus by grace." },
{ ref: "Ephesians 1:7", text: "In Him we have redemption through His blood, the forgiveness of sins according to the riches of His grace." },
{ ref: "Philippians 1:21", text: "For to me, to live is Christ and to die is gain; my life belongs fully to Him." },
{ ref: "Colossians 3:15", text: "Let the peace of Christ rule in your hearts, since you were called to peace as one body." },
{ ref: "1 Thessalonians 5:11", text: "Encourage one another and build each other up, just as you are already doing in love and faith." },
{ ref: "2 Thessalonians 1:11", text: "We constantly pray that God may make you worthy of His calling and fulfill your every act of faith." },
{ ref: "1 Timothy 1:15", text: "Christ Jesus came into the world to save sinners, of whom I am the worst and most unworthy." },
{ ref: "2 Timothy 4:7", text: "I have fought the good fight, finished the race, and kept the faith until the end in perseverance." },
{ ref: "Titus 2:7", text: "Set an example by doing what is good; show integrity, seriousness, and soundness in your teaching always." },
{ ref: "Hebrews 2:18", text: "Because He Himself suffered when tempted, He is able to help those who are being tempted in weakness." },
{ ref: "Hebrews 11:6", text: "Without faith it is impossible to please God, for whoever comes to Him must believe He rewards seekers." },
{ ref: "Hebrews 13:8", text: "Jesus Christ is the same yesterday, today, and forever; His truth and love never change or fade." },
{ ref: "James 1:17", text: "Every good and perfect gift comes from above, from the Father of lights who does not change." },
{ ref: "1 Peter 1:24", text: "All people are like grass, but the word of the Lord endures forever and stands unshaken through time." },
{ ref: "2 Peter 3:18", text: "Grow in the grace and knowledge of our Lord Jesus Christ. To Him be glory forever and ever." },
{ ref: "1 John 5:14", text: "This is the confidence we have in approaching God: that if we ask anything, He hears and responds." },
{ ref: "Revelation 1:3", text: "Blessed is the one who reads and keeps the words of this prophecy, for the time of fulfillment is near." },
{ ref: "Revelation 5:13", text: "To Him who sits on the throne and to the Lamb be praise, honor, and glory forever and ever." },
{ ref: "Revelation 22:12", text: "Behold, I am coming soon! My reward is with Me, and I will repay each person accordingly." },
{ ref: "Genesis 12:2", text: "I will make you into a great nation, bless you, and make your name great so you bless others." },
{ ref: "Genesis 15:6", text: "Abram believed the Lord, and it was credited to him as righteousness through his faith and trust in God." },
{ ref: "Genesis 24:27", text: "Blessed be the Lord, who has not abandoned His steadfast love and faithfulness toward His servant Abraham." },
{ ref: "Exodus 14:14", text: "The Lord will fight for you; you need only to be still and trust in His mighty power." },
{ ref: "Exodus 33:14", text: "My presence will go with you, and I will give you rest, says the Lord to His people." },
{ ref: "Leviticus 26:12", text: "I will walk among you and be your God, and you will be My people forever." },
{ ref: "Numbers 6:25", text: "The Lord make His face shine upon you and be gracious to you, filling your life with peace." },
{ ref: "Deuteronomy 4:29", text: "If you seek the Lord with all your heart and soul, you will surely find Him in mercy." },
{ ref: "Deuteronomy 8:18", text: "Remember the Lord your God, for it is He who gives you power to gain wealth and blessing." },
{ ref: "Joshua 1:9", text: "Be strong and courageous; do not be afraid or discouraged, for the Lord is with you always." },
{ ref: "Judges 6:12", text: "The angel of the Lord appeared and said, 'The Lord is with you, mighty warrior of faith and courage!'" },
{ ref: "Ruth 1:16", text: "Where you go, I will go; your people will be my people, and your God my God forever." },
{ ref: "1 Samuel 15:22", text: "To obey is better than sacrifice, and to heed is better than the fat of rams in worship." },
{ ref: "2 Samuel 22:31", text: "As for God, His way is perfect; He is a shield to all who take refuge in Him." },
{ ref: "1 Kings 8:61", text: "Let your heart be fully committed to the Lord our God, walking in His decrees faithfully every day." },
{ ref: "2 Kings 20:5", text: "I have heard your prayer and seen your tears; I will heal you, declares the Lord in compassion." },
{ ref: "1 Chronicles 16:11", text: "Seek the Lord and His strength; seek His presence continually and you will find peace everlasting." },
{ ref: "2 Chronicles 7:14", text: "If My people humble themselves and pray, I will forgive their sin and heal their land by grace." },
{ ref: "Ezra 3:11", text: "With praise and thanksgiving they sang to the Lord, 'He is good; His love endures forever toward Israel!'" },
{ ref: "Nehemiah 8:10", text: "Do not grieve, for the joy of the Lord is your strength and the source of your courage." },
{ ref: "Esther 4:14", text: "Perhaps you have come to your royal position for such a time as this, to fulfill God’s purpose." },
{ ref: "Job 19:25", text: "I know that my Redeemer lives, and in the end, He will stand upon the earth victorious forever." },
{ ref: "Psalm 16:8", text: "I keep my eyes always on the Lord; with Him at my right hand, I will not be shaken." },
{ ref: "Psalm 23:1", text: "The Lord is my shepherd; I shall not want, for He provides all my needs in perfect care." },
{ ref: "Psalm 27:1", text: "The Lord is my light and my salvation—whom shall I fear? The Lord is my stronghold forever." },
{ ref: "Psalm 37:4", text: "Delight yourself in the Lord, and He will give you the desires of your heart in His will." },
{ ref: "Psalm 46:1", text: "God is our refuge and strength, an ever-present help in trouble and times of great distress." },
{ ref: "Psalm 55:22", text: "Cast your burden on the Lord, and He will sustain you; He will never let the righteous fall." },
{ ref: "Psalm 91:11", text: "He will command His angels concerning you to guard you in all your ways, keeping you from harm." },
{ ref: "Psalm 100:4", text: "Enter His gates with thanksgiving and His courts with praise; give thanks to Him and bless His name." },
{ ref: "Psalm 119:105", text: "Your word is a lamp to my feet and a light to my path, guiding me in truth." },
{ ref: "Proverbs 3:5", text: "Trust in the Lord with all your heart and lean not on your own understanding, but acknowledge Him always." },
{ ref: "Proverbs 4:23", text: "Above all else, guard your heart, for everything you do flows from it and defines your life." },
{ ref: "Proverbs 11:25", text: "A generous person will prosper; whoever refreshes others will be refreshed by the goodness of God." },
{ ref: "Proverbs 17:22", text: "A cheerful heart is good medicine, but a crushed spirit dries up the bones and steals joy." },
{ ref: "Ecclesiastes 3:1", text: "To everything there is a season, a time for every purpose under heaven ordained by God’s wisdom." },
{ ref: "Isaiah 40:31", text: "Those who hope in the Lord will renew their strength; they will soar on wings like eagles with faith." },
{ ref: "Isaiah 55:6", text: "Seek the Lord while He may be found; call on Him while He is near and ready to forgive." },
{ ref: "Jeremiah 29:11", text: "For I know the plans I have for you, plans to prosper you and give you hope and future." },
{ ref: "Lamentations 3:22", text: "Because of the Lord’s great love we are not consumed; His mercies never fail or fade away." },
{ ref: "Ezekiel 36:26", text: "I will give you a new heart and put a new spirit in you, removing your heart of stone." },
{ ref: "Daniel 3:17", text: "The God we serve is able to deliver us from the blazing furnace, and He will rescue us." },
{ ref: "Hosea 6:3", text: "Let us press on to know the Lord; His coming is as sure as the dawn and rain." },
{ ref: "Joel 3:16", text: "The Lord will roar from Zion and be a refuge for His people and a stronghold for Israel." },
{ ref: "Amos 5:24", text: "Let justice roll on like a river, righteousness like a never-failing stream flowing from God’s throne." },
{ ref: "Micah 6:8", text: "What does the Lord require of you but to do justice, love mercy, and walk humbly with your God?" },
{ ref: "Nahum 1:7", text: "The Lord is good, a refuge in times of trouble; He cares for those who trust in Him." },
{ ref: "Habakkuk 3:19", text: "The Sovereign Lord is my strength; He makes my feet like a deer’s and enables me to tread heights." },
{ ref: "Zephaniah 3:17", text: "The Lord your God is with you; He rejoices over you with singing and delights in you deeply." },
{ ref: "Haggai 2:4", text: "Be strong, all you people of the land, and work, for I am with you, declares the Lord." },
{ ref: "Zechariah 4:6", text: "Not by might nor by power, but by My Spirit, says the Lord Almighty who strengthens His people." },
{ ref: "Malachi 3:10", text: "Bring the full tithe into the storehouse and see if I will not pour out blessing without measure." },
{ ref: "Matthew 5:9", text: "Blessed are the peacemakers, for they will be called children of God, reflecting His heart of reconciliation." },
{ ref: "Matthew 6:33", text: "Seek first the kingdom of God and His righteousness, and all these things will be added unto you." },
{ ref: "Matthew 11:28", text: "Come to Me, all you who are weary and burdened, and I will give you rest and peace." },
{ ref: "Genesis 22:14", text: "Abraham named that place The Lord Will Provide, for God Himself supplied what was needed in faith and obedience." },
{ ref: "Exodus 15:2", text: "The Lord is my strength and my song; He has become my salvation and my eternal victory through His power." },
{ ref: "Leviticus 20:26", text: "You shall be holy to Me, for I, the Lord, am holy and have set you apart for Myself." },
{ ref: "Numbers 23:19", text: "God is not a man that He should lie; His promises stand firm, and His word never fails." },
{ ref: "Deuteronomy 31:8", text: "The Lord Himself goes before you and will be with you; do not fear, for He never leaves you." },
{ ref: "Joshua 24:15", text: "Choose this day whom you will serve, but as for me and my house, we will serve the Lord faithfully." },
{ ref: "Judges 2:18", text: "Whenever the Lord raised up judges, He was with them, saving His people out of oppression through His compassion." },
{ ref: "Ruth 2:12", text: "May the Lord repay you for your kindness, and may you be richly rewarded under His wings of refuge." },
{ ref: "1 Samuel 2:2", text: "There is no one holy like the Lord; there is no rock like our God who never fails." },
{ ref: "2 Samuel 22:33", text: "It is God who arms me with strength and keeps my way secure through His faithful hand and power." },
{ ref: "1 Kings 2:3", text: "Observe what the Lord requires: walk in His ways and keep His commands, so you may prosper everywhere you go." },
{ ref: "2 Kings 17:39", text: "Worship the Lord your God; it is He who will deliver you from the hand of every enemy." },
{ ref: "1 Chronicles 29:11", text: "Yours, Lord, is the greatness, power, glory, victory, and majesty; everything in heaven and earth is Yours alone." },
{ ref: "2 Chronicles 16:9", text: "The eyes of the Lord search the whole earth to strengthen those whose hearts are fully committed to Him." },
{ ref: "Ezra 8:22", text: "The gracious hand of our God is on everyone who looks to Him, but His power opposes the proud." },
{ ref: "Nehemiah 4:20", text: "Wherever you hear the sound of the trumpet, join us there; our God will fight for us faithfully." },
{ ref: "Esther 8:16", text: "For the Jews it was a time of happiness and joy, gladness and honor, through God’s mighty deliverance." },
{ ref: "Job 5:11", text: "He sets the lowly on high and lifts those who mourn to safety and hope by His mercy." },
{ ref: "Job 22:21", text: "Submit to God and be at peace with Him; in this way prosperity and blessing will come to you." },
{ ref: "Psalm 9:10", text: "Those who know Your name trust in You, for You, Lord, never forsake those who seek You sincerely." },
{ ref: "Psalm 18:30", text: "As for God, His way is perfect; the Lord’s word is flawless; He shields all who take refuge in Him." },
{ ref: "Psalm 31:24", text: "Be strong and take heart, all you who hope in the Lord, for His love endures forever." },
{ ref: "Psalm 34:8", text: "Taste and see that the Lord is good; blessed is the one who takes refuge in Him faithfully." },
{ ref: "Psalm 62:8", text: "Trust in Him at all times, you people; pour out your hearts to Him, for God is our refuge." },
{ ref: "Psalm 103:12", text: "As far as the east is from the west, so far has He removed our transgressions from us in mercy." },
{ ref: "Psalm 119:11", text: "I have hidden Your word in my heart that I might not sin against You, O faithful Lord." },
{ ref: "Proverbs 10:22", text: "The blessing of the Lord brings true wealth, and He adds no sorrow or burden along with it." },
{ ref: "Proverbs 14:27", text: "The fear of the Lord is a fountain of life, turning one away from the snares of death." },
{ ref: "Proverbs 19:21", text: "Many are the plans in a person’s heart, but it is the Lord’s purpose that prevails eternally." },
{ ref: "Ecclesiastes 7:14", text: "When times are good, be joyful; when times are bad, consider that God made both to shape wisdom." },
{ ref: "Song of Solomon 2:16", text: "My beloved is mine and I am his; he browses among the lilies with gentle love and devotion." },
{ ref: "Isaiah 12:2", text: "Surely God is my salvation; I will trust and not be afraid, for the Lord is my strength and song." },
{ ref: "Isaiah 26:3", text: "You keep in perfect peace those whose minds are steadfast because they trust in You, O Lord." },
{ ref: "Isaiah 43:2", text: "When you pass through waters, I will be with you; rivers will not sweep over you, says the Lord." },
{ ref: "Isaiah 54:10", text: "Though the mountains be shaken, My unfailing love for you will not be removed, says the Lord." },
{ ref: "Jeremiah 17:7", text: "Blessed is the one who trusts in the Lord, whose confidence is in Him and not in human strength." },
{ ref: "Jeremiah 33:3", text: "Call to Me and I will answer you and tell you great and unsearchable things you do not know." },
{ ref: "Lamentations 3:25", text: "The Lord is good to those who hope in Him, to the soul that seeks Him diligently and patiently." },
{ ref: "Ezekiel 34:11", text: "For this is what the Sovereign Lord says: I Myself will search for My sheep and look after them." },
{ ref: "Daniel 6:27", text: "He rescues and saves; He performs signs and wonders in heaven and on earth, delivering His faithful servants." },
{ ref: "Hosea 14:9", text: "The ways of the Lord are right; the righteous walk in them, but the rebellious stumble and fall away." },
{ ref: "Joel 2:13", text: "Rend your heart and not your garments; return to the Lord, for He is gracious and compassionate always." },
{ ref: "Amos 4:13", text: "He who forms mountains and creates the wind declares to man what his thoughts are—the Lord Almighty reigns." },
{ ref: "Micah 7:18", text: "Who is a God like You, pardoning iniquity and showing mercy? You delight in steadfast love and forgiveness." },
{ ref: "Nahum 1:15", text: "Look, there on the mountains, the feet of one who brings good news and proclaims peace through God’s victory." },
{ ref: "Habakkuk 2:4", text: "The righteous will live by his faith, trusting in God’s promises through every trial and every season." },
{ ref: "Zephaniah 2:3", text: "Seek the Lord, all you humble of the land; seek righteousness and humility, and you may be sheltered." },
{ ref: "Haggai 1:7", text: "This is what the Lord Almighty says: Give careful thought to your ways and align them with My will." },
{ ref: "Zechariah 8:13", text: "Do not be afraid, but let your hands be strong; you will be a blessing among nations, says the Lord." },
{ ref: "Malachi 4:2", text: "For you who revere My name, the sun of righteousness will rise with healing in its wings forever." },
{ ref: "Matthew 4:4", text: "Man shall not live on bread alone, but on every word that comes from the mouth of God Almighty." },
{ ref: "Matthew 7:7", text: "Ask and it will be given to you; seek and you will find; knock and the door will be opened." },
{ ref: "Matthew 9:13", text: "I desire mercy, not sacrifice; for I have come to call sinners, not the righteous, into repentance and grace." },
{ ref: "Matthew 19:26", text: "With man this is impossible, but with God all things are possible through His power and unfailing love." },
{ ref: "Mark 8:34", text: "Whoever wants to be My disciple must deny themselves, take up their cross, and follow Me faithfully each day." },
{ ref: "Mark 10:27", text: "With man it is impossible, but not with God; all things are possible through His limitless strength and mercy." },
{ ref: "Luke 6:38", text: "Give, and it will be given to you—a good measure, pressed down, shaken together, and running over abundantly." },
{ ref: "Luke 9:23", text: "If anyone would come after Me, let them deny themselves, take up their cross daily, and follow Me faithfully." },
{ ref: "John 6:35", text: "I am the bread of life; whoever comes to Me will never hunger or thirst but be satisfied eternally." },
{ ref: "John 10:10", text: "The thief comes to steal and destroy; I came that they may have life abundantly, full and eternal." },
{ ref: "John 13:35", text: "By this everyone will know that you are My disciples, if you love one another with true compassion." },
{ ref: "Acts 2:21", text: "Everyone who calls on the name of the Lord will be saved, redeemed by grace through faith alone." },
{ ref: "Acts 20:35", text: "It is more blessed to give than to receive; generosity reflects the heart of Christ in humble service." },
{ ref: "Romans 1:16", text: "I am not ashamed of the gospel, for it is the power of God for salvation to everyone who believes." },
{ ref: "Romans 5:8", text: "God demonstrates His love for us in this: while we were still sinners, Christ died for us in grace." },
{ ref: "Romans 10:9", text: "If you declare with your mouth Jesus is Lord and believe in your heart, you will be saved eternally." },
{ ref: "Romans 12:12", text: "Be joyful in hope, patient in affliction, faithful in prayer, trusting God’s timing and strength in all things." },
{ ref: "1 Corinthians 1:9", text: "God is faithful, who has called you into fellowship with His Son, Jesus Christ our Lord forevermore." },
{ ref: "1 Corinthians 10:13", text: "God is faithful; He will not let you be tempted beyond what you can bear but provide a way out." },
{ ref: "2 Corinthians 4:18", text: "We fix our eyes not on what is seen, but unseen; for what is unseen is eternal and everlasting." },
{ ref: "Galatians 5:22", text: "The fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control." },
{ ref: "Ephesians 3:20", text: "To Him who is able to do immeasurably more than all we ask or imagine, be glory forever and ever." },
{ ref: "Philippians 1:6", text: "He who began a good work in you will carry it on to completion until the day of Christ Jesus." },
{ ref: "Philippians 2:3", text: "Do nothing out of selfish ambition, but in humility value others above yourselves as Christ taught us." },
{ ref: "Colossians 1:17", text: "He is before all things, and in Him all things hold together, sustained by His eternal word of power." },
{ ref: "1 Thessalonians 4:16", text: "The Lord Himself will descend from heaven with a loud command and the trumpet call of God’s glory." },
{ ref: "2 Thessalonians 2:16", text: "May our Lord Jesus Christ Himself encourage your hearts and strengthen you in every good word and deed." },
{ ref: "1 Timothy 6:12", text: "Fight the good fight of faith; take hold of eternal life to which you were called through confession in Christ." },
{ ref: "2 Timothy 2:15", text: "Do your best to present yourself to God as one approved, rightly handling the word of truth with integrity." },
{ ref: "Titus 3:5", text: "He saved us, not because of righteous things we had done, but because of His mercy and renewing Spirit." },
{ ref: "Hebrews 10:24", text: "Let us consider how we may spur one another toward love and good deeds that reflect Christ’s heart." },
{ ref: "James 4:7", text: "Submit yourselves to God. Resist the devil, and he will flee from you under God’s mighty protection." },
{ ref: "1 Peter 2:9", text: "You are a chosen people, a royal priesthood, called out of darkness into His wonderful light and grace." },
{ ref: "1 John 4:19", text: "We love because He first loved us, teaching us how to love unconditionally and serve one another faithfully." },
{ ref: "Revelation 1:8", text: "I am the Alpha and the Omega, says the Lord God, who is, who was, and who is to come." },
{ ref: "Genesis 28:15", text: "I am with you and will watch over you wherever you go, and I will bring you back safely." },
{ ref: "Exodus 20:12", text: "Honor your father and your mother, so that your days may be long in the land the Lord gives you." },
{ ref: "Leviticus 19:18", text: "Love your neighbor as yourself; I am the Lord who calls you to mercy and compassion in truth." },
{ ref: "Numbers 6:24", text: "The Lord bless you and keep you; may His protection and favor rest continually upon your life." },
{ ref: "Deuteronomy 6:5", text: "Love the Lord your God with all your heart, with all your soul, and with all your strength always." },
{ ref: "Joshua 23:10", text: "One of you routs a thousand, because the Lord your God fights for you as He promised faithfully." },
{ ref: "Judges 5:31", text: "May all who love the Lord be like the sun when it rises in its strength and radiant glory." },
{ ref: "Ruth 4:14", text: "Praise be to the Lord, who this day has not left you without a redeemer to restore your life." },
{ ref: "1 Samuel 16:7", text: "The Lord does not look at outward appearance but at the heart, where true beauty and faithfulness dwell." },
{ ref: "2 Samuel 7:28", text: "Sovereign Lord, You are God; Your covenant is trustworthy, and Your promises are good and everlasting truth." },
{ ref: "1 Kings 3:9", text: "Give Your servant a discerning heart to govern Your people and to distinguish between right and wrong faithfully." },
{ ref: "2 Kings 19:19", text: "Save us, Lord, so all kingdoms of the earth may know that You alone, O Lord, are God." },
{ ref: "1 Chronicles 16:34", text: "Give thanks to the Lord, for He is good; His love endures forever and fills the earth with grace." },
{ ref: "2 Chronicles 20:15", text: "Do not be afraid or discouraged, for the battle is not yours, but God’s, who fights on your behalf." },
{ ref: "Ezra 7:10", text: "Ezra devoted himself to the study and observance of the Law of the Lord and its teaching in Israel." },
{ ref: "Nehemiah 1:5", text: "Lord, You are great and awesome, keeping Your covenant of love with those who love and obey Your commands." },
{ ref: "Esther 9:22", text: "Days of joy and gladness, feasting and celebration—gifts sent to one another in remembrance of God’s deliverance." },
{ ref: "Job 23:10", text: "He knows the way that I take; when He has tested me, I will come forth as pure gold." },
{ ref: "Job 42:2", text: "I know that You can do all things; no purpose of Yours can be thwarted or hindered by man." },
{ ref: "Psalm 4:8", text: "In peace I will lie down and sleep, for You alone, Lord, make me dwell in safety and rest." },
{ ref: "Psalm 19:14", text: "May the words of my mouth and meditation of my heart be pleasing in Your sight, O Lord, my Rock." },
{ ref: "Psalm 27:14", text: "Wait for the Lord; be strong and take heart, and wait patiently for His timing and faithful guidance." },
{ ref: "Psalm 37:7", text: "Be still before the Lord and wait patiently for Him; do not fret when others seem to prosper." },
{ ref: "Psalm 42:11", text: "Why, my soul, are you downcast? Put your hope in God, for I will praise Him, my Savior." },
{ ref: "Psalm 63:3", text: "Because Your love is better than life, my lips will glorify You and my soul will be satisfied completely." },
{ ref: "Psalm 91:4", text: "He will cover you with His feathers, and under His wings you will find refuge and steadfast protection always." },
{ ref: "Psalm 103:2", text: "Praise the Lord, my soul, and forget not all His benefits—He forgives, heals, redeems, and crowns with love." },
{ ref: "Psalm 139:14", text: "I praise You because I am fearfully and wonderfully made; Your works are wonderful, and I know that fully." },
{ ref: "Proverbs 1:7", text: "The fear of the Lord is the beginning of knowledge, but fools despise wisdom and instruction that leads to life." },
{ ref: "Proverbs 12:25", text: "Anxiety weighs down the heart, but a kind word cheers it up and brings light and comfort again." },
{ ref: "Proverbs 16:3", text: "Commit to the Lord whatever you do, and He will establish your plans according to His divine purpose." },
{ ref: "Proverbs 27:17", text: "As iron sharpens iron, so one person sharpens another, building strength, wisdom, and character through godly fellowship." },
{ ref: "Ecclesiastes 9:10", text: "Whatever your hand finds to do, do it with all your might, for life is fleeting and sacred." },
{ ref: "Isaiah 1:18", text: "Though your sins are like scarlet, they shall be white as snow through the mercy and cleansing of the Lord." },
{ ref: "Isaiah 9:6", text: "For unto us a child is born, a Son given; He will be called Prince of Peace and Mighty God." },
{ ref: "Isaiah 41:10", text: "Do not fear, for I am with you; do not be dismayed, for I will strengthen and uphold you." },
{ ref: "Isaiah 58:11", text: "The Lord will guide you always; He will satisfy your needs and strengthen your frame like a well-watered garden." },
{ ref: "Jeremiah 1:5", text: "Before I formed you in the womb I knew you; before birth, I set you apart for My purpose." },
{ ref: "Jeremiah 32:17", text: "Ah, Sovereign Lord, You made the heavens and earth; nothing is too hard or impossible for You to accomplish." },
{ ref: "Lamentations 3:23", text: "They are new every morning; great is Your faithfulness that renews our strength and hope with each rising day." },
{ ref: "Ezekiel 37:5", text: "This is what the Sovereign Lord says: I will make breath enter you, and you will come to life again." },
{ ref: "Daniel 2:22", text: "He reveals deep and hidden things; He knows what lies in darkness, and light dwells with Him eternally and brightly." },
{ ref: "Hosea 10:12", text: "Sow righteousness for yourselves, reap the fruit of unfailing love, for it is time to seek the Lord wholeheartedly." },
{ ref: "Joel 2:28", text: "I will pour out My Spirit on all people; your sons and daughters will prophesy and dream dreams of hope." },
{ ref: "Amos 5:14", text: "Seek good, not evil, that you may live; then the Lord God Almighty will be with you and bless." },
{ ref: "Micah 4:5", text: "All nations may walk in the name of their gods, but we will walk in the Lord’s name forever." },
{ ref: "Habakkuk 2:14", text: "The earth will be filled with the knowledge of the glory of the Lord as waters cover the sea." },
{ ref: "Zephaniah 3:9", text: "Then I will purify the lips of the peoples, that all may call on the Lord and serve Him together." },
{ ref: "Haggai 2:9", text: "The glory of this latter house will be greater than the former, says the Lord, granting peace and favor." },
{ ref: "Zechariah 9:9", text: "Rejoice greatly, daughter Zion; your King comes righteous and victorious, humble and riding on a donkey of peace." },
{ ref: "Malachi 3:6", text: "I the Lord do not change; so you, descendants of Jacob, are not destroyed by My faithful covenant promise." },
{ ref: "Matthew 5:14", text: "You are the light of the world; a city on a hill cannot be hidden but shines for all to see." },
{ ref: "Matthew 11:29", text: "Take My yoke upon you and learn from Me, for I am gentle and humble in heart, bringing rest." },
{ ref: "Matthew 28:20", text: "Surely I am with you always, to the very end of the age; My presence never leaves nor fades." },
{ ref: "Mark 9:23", text: "Everything is possible for the one who believes; faith unlocks the impossible through the power of God’s presence." },
{ ref: "Luke 1:45", text: "Blessed is she who has believed that the Lord would fulfill His promises to her with steadfast faith." },
{ ref: "Luke 11:9", text: "Ask and it will be given to you; seek and you will find; knock and the door will open." },
{ ref: "Luke 18:27", text: "What is impossible with man is possible with God, for His power surpasses every limitation of human strength." },
{ ref: "John 1:5", text: "The light shines in the darkness, and the darkness has not overcome it because Christ’s light endures forever." },
{ ref: "John 7:38", text: "Whoever believes in Me, rivers of living water will flow from within them, filling hearts with life and joy." },
{ ref: "John 15:5", text: "I am the vine; you are the branches. Remain in Me, and you will bear much fruit abundantly." },
{ ref: "Acts 16:31", text: "Believe in the Lord Jesus, and you will be saved—you and your household will share in His salvation." },
{ ref: "Romans 8:1", text: "Therefore, there is now no condemnation for those who are in Christ Jesus, freed by grace and faith." },
{ ref: "Romans 15:13", text: "May the God of hope fill you with joy and peace as you trust in Him completely through the Spirit." },
{ ref: "1 Corinthians 15:58", text: "Stand firm, let nothing move you; always give yourselves fully to the work of the Lord and His purpose." },
{ ref: "2 Corinthians 9:8", text: "God is able to bless you abundantly, so you have all you need for every good work He ordains." },
{ ref: "Galatians 6:9", text: "Let us not grow weary in doing good, for at the proper time we will reap a harvest if steadfast." },
{ ref: "Ephesians 4:2", text: "Be completely humble and gentle; be patient, bearing with one another in love as Christ bore with you." },
{ ref: "Philippians 3:14", text: "I press on toward the goal to win the prize for which God has called me heavenward in Christ." },
{ ref: "Colossians 3:2", text: "Set your minds on things above, not on earthly things, for your life is hidden with Christ in God." },
{ ref: "1 Thessalonians 5:11", text: "Encourage one another and build each other up, just as you are doing, in unity and love through Christ." },
{ ref: "2 Thessalonians 3:13", text: "As for you, never tire of doing what is good; persevere in righteousness and faith through Christ Jesus." },
{ ref: "1 Timothy 1:17", text: "To the King eternal, immortal, invisible, the only God, be honor and glory forever and ever. Amen." },
{ ref: "2 Timothy 4:7", text: "I have fought the good fight, finished the race, kept the faith, trusting Christ for my eternal crown." },
{ ref: "Titus 2:7", text: "In everything set them an example by doing what is good; show integrity, seriousness, and soundness in teaching." },
{ ref: "Philemon 1:25", text: "The grace of the Lord Jesus Christ be with your spirit, bringing peace, joy, and strength in faith." },
{ ref: "Hebrews 11:1", text: "Now faith is confidence in what we hope for and assurance about what we do not see clearly yet." },
{ ref: "James 1:22", text: "Do not merely listen to the word, and so deceive yourselves; do what it says through obedient faith." },
{ ref: "1 Peter 1:8", text: "Though you have not seen Him, you love Him and are filled with an inexpressible and glorious joy everlasting." },
{ ref: "2 Peter 1:5", text: "Make every effort to add to your faith goodness, knowledge, self-control, perseverance, godliness, brotherly kindness, and love." },
{ ref: "1 John 4:4", text: "Greater is He who is in you than he who is in the world, empowering you to overcome all evil." },
{ ref: "Jude 1:21", text: "Keep yourselves in God’s love as you wait for the mercy of our Lord Jesus Christ to bring eternal life." },
{ ref: "Revelation 3:20", text: "Here I am! I stand at the door and knock. If anyone hears My voice, I will come in." },
{ ref: "Revelation 22:13", text: "I am the Alpha and the Omega, the First and the Last, the Beginning and the End, eternal King." },
{ ref: "Genesis 12:2", text: "God calls us to step out in faith, promising to bless and make us a blessing wherever we go." },
{ ref: "Genesis 22:14", text: "The Lord provides what we cannot; He meets needs in ways that reveal His perfect timing and endless grace." },
{ ref: "Exodus 14:14", text: "When we feel powerless, God fights for us; our stillness becomes the space where His victory shines brightest." },
{ ref: "Leviticus 20:7", text: "Be holy because God is holy; set apart your heart and live reflecting His purity in thought and action." },
{ ref: "Numbers 23:19", text: "God never lies nor changes His mind; His promises stand firm, trustworthy, and forever sure across generations." },
{ ref: "Deuteronomy 31:8", text: "The Lord Himself goes before you; He will never leave nor forsake you, so take courage in His presence." },
{ ref: "Joshua 24:15", text: "Choose today whom you will serve; as for me and my house, we will serve the Lord wholeheartedly." },
{ ref: "Judges 6:12", text: "The Lord calls even the fearful ‘mighty warrior,’ reminding us our strength comes from Him, not from ourselves." },
{ ref: "Ruth 1:16", text: "True love stays through loss; Ruth’s loyalty mirrors God’s steadfast love that clings to us and never leaves." },
{ ref: "1 Samuel 17:47", text: "The battle belongs to the Lord; victory comes not by sword or strength but through faith in His power." },
{ ref: "2 Samuel 22:31", text: "God’s way is perfect; His word flawless; He shields all who take refuge in His unshakable protection." },
{ ref: "1 Kings 8:23", text: "No God compares to You, keeping covenant and mercy with all who walk before You with wholehearted devotion." },
{ ref: "2 Kings 6:17", text: "Open our eyes, Lord, to see Your armies around us, stronger than any fear or visible threat." },
{ ref: "1 Chronicles 29:11", text: "Yours, Lord, is greatness and glory; all things in heaven and earth belong to You alone, eternal King." },
{ ref: "2 Chronicles 7:14", text: "If we humble ourselves and pray, God will hear, forgive, and heal our land with His gracious mercy." },
{ ref: "Ezra 8:22", text: "God’s hand is on all who seek Him earnestly, granting favor, protection, and guidance in every uncertain path." },
{ ref: "Nehemiah 8:10", text: "Do not grieve, for the joy of the Lord is your strength; rejoice even amid trials, for God sustains." },
{ ref: "Esther 4:14", text: "Perhaps you were born for such a time as this—to bring courage, faith, and hope into fearful circumstances." },
{ ref: "Job 19:25", text: "I know my Redeemer lives; even in loss, my heart rests on His promise of resurrection and restoration." },
{ ref: "Psalm 9:1", text: "I will give thanks with all my heart; I will tell of Your wonderful deeds and faithful kindness." },
{ ref: "Psalm 18:2", text: "The Lord is my rock, fortress, and deliverer; I take refuge in Him, my strength and stronghold forever." },
{ ref: "Psalm 34:8", text: "Taste and see that the Lord is good; blessed is the one who trusts and delights in His care." },
{ ref: "Psalm 46:1", text: "God is our refuge and strength, a present help in trouble; therefore we will not fear the storms ahead." },
{ ref: "Psalm 100:4", text: "Enter His gates with thanksgiving, His courts with praise; give thanks and bless His name with joyful hearts." },
{ ref: "Psalm 119:105", text: "Your word is a lamp for my feet and a light for my path, guiding me in every step." },
{ ref: "Proverbs 3:6", text: "Acknowledge Him in all your ways, and He will direct your paths toward peace and fruitful purpose." },
{ ref: "Proverbs 4:23", text: "Guard your heart above all else, for from it flow the springs of life shaping all your choices." },
{ ref: "Proverbs 11:25", text: "A generous person will prosper; whoever refreshes others will themselves be refreshed with joy and blessing." },
{ ref: "Ecclesiastes 3:11", text: "God makes everything beautiful in its time; He places eternity in our hearts to awaken hope and wonder." },
{ ref: "Song of Songs 2:16", text: "I am my beloved’s, and my beloved is mine; love that mirrors divine commitment and everlasting faithfulness." },
{ ref: "Isaiah 26:3", text: "You keep in perfect peace those whose minds are steadfast, because they trust and rest fully in You." },
{ ref: "Isaiah 40:31", text: "Those who hope in the Lord will renew their strength, rising on wings like eagles, running without growing weary." },
{ ref: "Isaiah 55:8", text: "My thoughts are higher than your thoughts, My ways beyond your ways, says the Lord of wisdom eternal." },
{ ref: "Jeremiah 17:7", text: "Blessed is the one who trusts in the Lord; whose confidence is rooted deeply in His unfailing presence." },
{ ref: "Lamentations 3:25", text: "The Lord is good to those who hope in Him, to the soul that seeks Him patiently and faithfully." },
{ ref: "Ezekiel 36:26", text: "I will give you a new heart and put a new spirit in you, softening what was once stone." },
{ ref: "Daniel 6:27", text: "He rescues and saves; He performs signs and wonders in heaven and earth, delivering those who trust Him." },
{ ref: "Hosea 14:4", text: "I will heal their waywardness and love them freely, for My anger has turned away and mercy has come." },
{ ref: "Joel 2:12", text: "Return to Me with all your heart, with fasting and weeping, for I am gracious and abounding in love." },
{ ref: "Amos 5:24", text: "Let justice roll on like a river, righteousness like a never-failing stream flowing from hearts aligned with God." },
{ ref: "Micah 7:7", text: "I will watch for the Lord; I will wait for the God of my salvation; my God will hear me." },
{ ref: "Nahum 1:7", text: "The Lord is good, a strong refuge in times of trouble; He cares for those who trust Him." },
{ ref: "Habakkuk 3:19", text: "The Sovereign Lord is my strength; He makes my feet like the deer’s, enabling me to go higher." },
{ ref: "Zephaniah 3:17", text: "The Lord rejoices over you with singing; He will quiet you with His love and renew your heart." },
{ ref: "Haggai 1:13", text: "I am with you, declares the Lord; take courage and rebuild what has been broken through faith and obedience." },
{ ref: "Zechariah 4:6", text: "Not by might nor by power, but by My Spirit, says the Lord Almighty, accomplishing what seems impossible." },
{ ref: "Malachi 4:2", text: "The Sun of righteousness will rise with healing in His wings, and you will go out rejoicing in freedom." },
{ ref: "Matthew 6:33", text: "Seek first the kingdom of God and His righteousness, and all these things will be added to you abundantly." },
{ ref: "Matthew 7:12", text: "Do to others what you would have them do to you; this sums up the law and the prophets." },
{ ref: "Matthew 19:26", text: "With man this is impossible, but with God all things are possible; His power surpasses human limitation." },
{ ref: "Mark 10:27", text: "Jesus reminded them that with God, nothing is beyond reach; His ability transforms impossibility into blessing." },
{ ref: "Luke 6:38", text: "Give, and it will be given to you; a good measure, pressed down, running over, poured into your lap." },
{ ref: "Luke 12:32", text: "Do not fear, little flock, for your Father delights to give you the kingdom and eternal security in Him." },
{ ref: "John 3:17", text: "God sent His Son not to condemn the world but to save it, revealing the depth of divine love." },
{ ref: "John 8:12", text: "I am the light of the world; whoever follows Me will never walk in darkness but have life’s light." },
{ ref: "John 10:10", text: "The thief comes to steal and destroy, but I came that you may have abundant, overflowing life through Me." },
{ ref: "John 13:34", text: "Love one another as I have loved you; by this love the world will know you are Mine." },
{ ref: "John 14:27", text: "My peace I give you; not as the world gives. Let not your hearts be troubled nor afraid." },
{ ref: "Acts 1:8", text: "You will receive power when the Holy Spirit comes on you; you will be witnesses to the ends of earth." },
{ ref: "Acts 20:35", text: "It is more blessed to give than to receive; generosity fills the heart with the joy of Christ." },
{ ref: "Romans 5:8", text: "While we were still sinners, Christ died for us, proving the boundless love and mercy of our faithful Savior." },
{ ref: "Romans 12:12", text: "Be joyful in hope, patient in affliction, faithful in prayer, trusting God’s timing and steadfast grace through all." },
{ ref: "1 Corinthians 10:31", text: "Whatever you do, do it all for the glory of God, making your life an offering of praise." },
{ ref: "1 Corinthians 13:7", text: "Love bears all things, believes all things, hopes all things, endures all things; love never fails nor fades." },
{ ref: "2 Corinthians 4:17", text: "Our present troubles are light and momentary, producing an eternal glory that far outweighs everything we face now." },
{ ref: "Galatians 5:22", text: "The fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control." },
{ ref: "Ephesians 3:20", text: "God is able to do immeasurably more than we ask or imagine, according to His power working within us." },
{ ref: "Philippians 2:3", text: "Do nothing from selfish ambition; in humility, value others above yourselves, reflecting Christ’s servant-hearted example daily." },
{ ref: "Philippians 4:13", text: "I can do all things through Christ who strengthens me, empowering me to persevere through every trial faithfully." },
{ ref: "Colossians 3:17", text: "Whatever you do, whether in word or deed, do it in Jesus’ name, giving thanks to God through Him." },
{ ref: "1 Thessalonians 5:16", text: "Rejoice always, pray continually, and give thanks in everything; this is God’s will for you in Christ Jesus." },
{ ref: "2 Thessalonians 3:16", text: "May the Lord of peace Himself give you peace at all times and in every situation through His presence." },
{ ref: "1 Timothy 4:12", text: "Set an example for believers in speech, conduct, love, faith, and purity, shining Christ’s character in all." },
{ ref: "2 Timothy 1:7", text: "God gave us not a spirit of fear, but of power, love, and sound mind through His abiding Spirit." },
{ ref: "Titus 3:5", text: "He saved us not by righteous works but by His mercy, through the washing and renewal of the Holy Spirit." },
{ ref: "Philemon 1:7", text: "Your love has refreshed the hearts of the saints; may your kindness continue to bring joy and encouragement." },
{ ref: "Hebrews 4:16", text: "Let us approach God’s throne of grace with confidence, to receive mercy and find grace to help in need." },
{ ref: "Hebrews 13:8", text: "Jesus Christ is the same yesterday, today, and forever; His faithfulness never changes and His promises endure eternally." },
{ ref: "James 1:5", text: "If any lacks wisdom, ask God who gives generously to all without finding fault, and it will be given." },
{ ref: "1 Peter 5:7", text: "Cast all your anxiety on Him because He cares for you more deeply than you can imagine." },
{ ref: "2 Peter 3:9", text: "The Lord is not slow in keeping His promise; He is patient, wanting everyone to come to repentance." },
{ ref: "1 John 1:9", text: "If we confess our sins, He is faithful to forgive and cleanse us from all unrighteousness completely." },
{ ref: "1 John 3:18", text: "Let us not love with words or speech only but with actions and truth that reflect God’s heart." },
{ ref: "Revelation 1:8", text: "I am the Alpha and Omega, says the Lord, who is, was, and is to come—the Almighty forever." },
{ ref: "Revelation 21:4", text: "He will wipe every tear from their eyes; there will be no more death, mourning, crying, or pain ever." },
{ ref: "Revelation 22:17", text: "The Spirit and the bride say, ‘Come.’ Whoever is thirsty, let them come and freely receive the water of life." },
];

function seededShuffle(array, seed) {
  let result = array.slice();
  let m = result.length, t, i;
  function random() {
    seed = (seed * 9301 + 49297) % 233280;
    return seed / 233280;
  }
  while (m) {
    i = Math.floor(random() * m--);
    t = result[m];
    result[m] = result[i];
    result[i] = t;
  }
  return result;
}

export function getVerseOfTheDay() {
  const now = new Date();
  const year = now.getFullYear();
  const startDate = new Date(year + '-01-01T00:00:00Z');
  const endDate = new Date(year + '-12-31T23:59:59Z');
  const diffDays = Math.floor((now - startDate) / (1000 * 60 * 60 * 24));
  const shuffled = seededShuffle(bibleVerses, year);
  const verseIndex = diffDays % shuffled.length;
  return shuffled[verseIndex];
}

export default bibleVerses;
